const test=require('node:test'),assert=require('node:assert/strict');
const {RunnerScope}=require('../../runtime/lifecycle/runner-scope.ts');
const {installGameLogs,installHostGameLogs}=require('../../runtime/characters/game-logs.ts');
const {classifyGameLog,showGameLog}=require('../../runtime/game-log-filters.ts');
test('routine messages are Info independently of errors and gold',()=>{
 for(const message of ['bankboi0: bankboi0 loaded generic merchant behavior','bankboi1: Searching for a path...','Get closer','GoldMajesty: Get closer','Waiting in line']){
  assert.equal(classifyGameLog(message),'info');
  assert.equal(showGameLog(classifyGameLog(message),{info:false}),false);
 }
 assert.equal(classifyGameLog('ReferenceError: receive_generated_map_chunk is not defined'),'errors');
 assert.equal(classifyGameLog('Received 100 gold'),'gold');
 assert.equal(showGameLog('other',{info:false}),false);
});
test('native filters occupy the existing log height and reinstall without duplicate controls or log entries',()=>{
 const {JSDOM}=require('../../.caracal/node_modules/jsdom');
 const dom=new JSDOM('<div id="bottomrightcorner"><div class="xpsui" style="position:relative;margin-bottom:-10px">XP</div><div id="gamelog" style="height:200px;width:300px;overflow:auto"></div></div>',{url:'https://example.test'});
 const doc=dom.window.document,log=doc.getElementById('gamelog');
 const host={document:doc,localStorage:dom.window.localStorage,add_log(message){const entry=doc.createElement('div');entry.className='gameentry';entry.innerHTML=message;log.appendChild(entry);}};
 installHostGameLogs(host,async()=>{});host.add_log('Get closer');
 installHostGameLogs(host,async()=>{});host.add_log('Failed to connect');
 assert.equal(doc.querySelectorAll('#party-game-log-panel').length,1);
 assert.equal(doc.getElementById('party-game-log-panel').style.height,'200px');
 assert.equal(doc.querySelectorAll('#party-game-log-filters').length,1);
 assert.match(doc.getElementById('party-game-log-layout').textContent,/margin-bottom:0 !important/);
 assert.equal(doc.getElementById('party-game-log-panel').style.width,'330px');
 assert.match(doc.getElementById('party-game-log-layout').textContent,/padding-top:0/);
 assert.equal(doc.querySelectorAll('#party-game-log-layout').length,1);
 assert.equal(log.querySelectorAll('.gameentry').length,2);
 const info=[...doc.querySelectorAll('button')].find(b=>b.textContent==='Info');info.click();
 assert.equal(log.children[0].style.display,'none');assert.equal(log.children[1].style.display,'');
 installHostGameLogs(host,async()=>{});
 assert.equal([...doc.querySelectorAll('button')].find(b=>b.textContent==='Info').getAttribute('aria-pressed'),'false');
 const panel=doc.getElementById('party-game-log-panel'),handle=doc.getElementById('party-game-log-resize');
 handle.setPointerCapture=()=>{};handle.releasePointerCapture=()=>{};
 const pointer=(type,x)=>handle['on'+type]({clientX:x,button:0,pointerId:1,preventDefault(){},stopPropagation(){}});
 pointer('pointerdown',600);pointer('pointermove',450);pointer('pointerup',450);
 assert.equal(panel.style.width,'480px');assert.equal(host.localStorage.getItem('party-game-log-width'),'480');
 installHostGameLogs(host,async()=>{});assert.equal(panel.style.width,'480px');
 assert.equal(doc.querySelectorAll('#party-game-log-resize').length,1);
 doc.getElementById('party-game-log-resize').dispatchEvent(new dom.window.MouseEvent('dblclick',{bubbles:true}));
 assert.equal(panel.style.width,'330px');
 let leaked=0;doc.addEventListener('mousedown',()=>leaked++);
 const selecting=new dom.window.MouseEvent('mousedown',{bubbles:true,cancelable:true});log.children[1].dispatchEvent(selecting);
 assert.equal(leaked,0);assert.equal(selecting.defaultPrevented,false);
 const copying=new dom.window.KeyboardEvent('keydown',{key:'c',ctrlKey:true,bubbles:true,cancelable:true});log.dispatchEvent(copying);
 assert.equal(copying.defaultPrevented,false);
 dom.window.close();
});
test('native logs preserve scrollback through appends, filtering, trimming and reinstall, then resume at bottom',()=>{
 const {JSDOM}=require('../../.caracal/node_modules/jsdom');
 const dom=new JSDOM('<div id="gamelog"></div>',{url:'https://example.test'});
 const doc=dom.window.document,log=doc.getElementById('gamelog');
 const visible=()=>[...log.children].filter(e=>e.style.display!=='none');
 Object.defineProperties(log,{clientHeight:{value:100},scrollHeight:{get:()=>visible().length*20}});
 log.getBoundingClientRect=()=>({top:100,bottom:200});
 let trim=false;
 const host={document:doc,add_log(message){
  const entry=doc.createElement('div');entry.className='gameentry';entry.innerHTML=message;
  entry.getBoundingClientRect=()=>{const top=100+visible().indexOf(entry)*20-log.scrollTop;return {top,bottom:top+20};};
  log.appendChild(entry);
  if(trim)log.firstElementChild.remove();
  log.scrollTop=log.scrollHeight-100;
 }};
 installHostGameLogs(host,async()=>{});
 for(let i=0;i<20;i++)host.add_log('message '+i);
 log.scrollTop=105;
 const anchor=log.children[5],offset=anchor.getBoundingClientRect().top;
 host.add_log('message appended');
 assert.equal(log.scrollTop,105);
 assert.equal(anchor.getBoundingClientRect().top,offset);
 trim=true;host.add_log('oldest trimmed');trim=false;
 assert.equal(log.scrollTop,85);
 assert.equal(anchor.getBoundingClientRect().top,offset);
 installHostGameLogs(host,async()=>{});host.add_log('after reinstall');
 assert.equal(log.scrollTop,85);
 host.__partyGameLogCapture.filters.gold=false;
 host.add_log('Received 100 gold');
 assert.equal(log.lastElementChild.style.display,'none');
 assert.equal(anchor.getBoundingClientRect().top,offset);
 log.scrollTop=log.scrollHeight-log.clientHeight-2;
 const nearBottom=log.scrollTop;host.add_log('still reading');
 assert.equal(log.scrollTop,nearBottom);
 log.scrollTop=log.scrollHeight-log.clientHeight;
 host.add_log('follow again');
 assert.equal(log.scrollTop,log.scrollHeight);
 log.scrollTop=0;host.add_log('reading oldest');assert.equal(log.scrollTop,0);
 dom.window.close();
});

test('headless logging uses host hook without recursive facade dispatch and survives CODE retirement',async()=>{
 const rendered=[],batches=[],host={add_log:message=>rendered.push(message),caracAL:{}};
 host.caracAL.install_game_logs=send=>installHostGameLogs(host,send);
 const firstScope=new RunnerScope(),first=installGameLogs(firstScope.facade(host),async e=>batches.push(e));
 for(let i=0;i<1500;i++)host.add_log('message '+i);
 await first.pulse();assert.equal(rendered.length,1500);assert.equal(batches[0].length,100);assert.equal(host.__partyGameLogCapture.queue.length,900);
 firstScope.dispose();const secondScope=new RunnerScope();let newBatches=0;
 const second=installGameLogs(secondScope.facade(host),async()=>newBatches++);
 host.add_log('after reload');await second.pulse();assert.equal(rendered.at(-1),'after reload');assert.equal(newBatches,1);
 secondScope.dispose();
});
