import { mkdir } from "node:fs/promises";
import { Access } from "./access.ts";
import { gateway } from "./gateway.ts";
import { listen } from "./listen.ts";
import { servicesHealthy } from "./health.ts";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Services } from "./services.ts";
import { updateHosting } from '../update/hosting.ts';
import { LocalTLS } from './tls.ts';
import { configureDashboardGateway } from '../dashboard/gateway-access.ts';
import { createLocalSteam } from '../steam/service.ts';
import { DebugInstances } from '../debug/service.ts';
import { loadManagedConsole } from '../console-build/bootstrap.ts';
configureDashboardGateway();
const root = fileURLToPath(new URL("../../", import.meta.url)),
  services = new Services();
const data = path.resolve(process.env.AL_DATA_DIR || path.join(root, ".build/hosting-data"));
await mkdir(data, { recursive: true });
const access = new Access(path.join(data, "access.json"));
await access.load();
const tls = new LocalTLS(root, data);
let steamServer: string | undefined;
const steam = createLocalSteam(root, data, 924, async () => steamServer ??= (process.platform === 'linux'
  ? `https://localhost:${tls.publicPort}` : `http://127.0.0.1:${process.env.AL_PORT || 3010}`) + '/bridge/' + await access.steam());
const managed = await loadManagedConsole(root, services, { dashboardPort: 3030, apiPort: 924 });
const server = gateway({ builds: managed.routes, steam, tls, access, debug: await new DebugInstances(root, path.join(data, 'debug')).load(), updates: await updateHosting(root, data), configured: () => true, healthy: () => servicesHealthy(true), dashboardPort: 3030, publicUrl: process.env.AL_PUBLIC_URL || undefined });
await listen(server, access);
await tls.start();
await managed.startGame({...process.env, AL_DATA_DIR: data});
const stop = () => {
  steam.stop();
  tls.stop();
  server.close();
  services.stop();
  void managed.stop();
  setTimeout(() => process.exit(0), 15000).unref();
};
process.once("SIGINT", stop);
process.once("SIGTERM", stop);
