export const setupPage = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Party Console setup</title>
<style>body{font:17px system-ui;background:#101318;color:#f4f4f5;max-width:760px;margin:40px auto;padding:20px}button,input,select,textarea{font:inherit;background:#232933;color:#fff;border:1px solid #8693a6;border-radius:6px;padding:10px;margin:8px 0}button{cursor:pointer}button:hover{background:#38465a}input,textarea{box-sizing:border-box;width:100%}textarea{height:130px}a{color:#93c5fd}code{overflow-wrap:anywhere}section{border:1px solid #596579;padding:18px;margin:20px 0}#error{color:#fca5a5;white-space:pre-wrap}label{display:block}</style></head><body>
<h1>Party Console</h1><p>Your bots run here. Steam and browsers connect over your home network.</p><p id="error" role="status"></p>
<section id="pair" hidden><h2>Pair this browser</h2><p>Open an invitation from an authorized browser or the server startup output.</p><button id="pairButton">Pair browser</button></section>
<main id="settings" hidden><section id="account"><h2>Connect your game account</h2><p>You only need to connect your account once. In the Adventure Land Steam client, log in to a character, open CODE, paste this line, and click Engage:</p><code>show_json(parent.user_id + "-" + parent.user_auth)</code><p>Copy the displayed session and paste it below.</p>
<label>Game session<input id="session" type="password" autocomplete="off"></label><label>Realm<select id="realm"><option>SR_USII</option><option>SR_USI</option><option>SR_USIII</option><option>SR_EUI</option><option>SR_EUII</option><option>SR_ASIAI</option></select></label><button id="connect">Connect account</button><p>Characters start disabled. Select offline characters in the dashboard to run them headless; leave Steam characters in Steam.</p></section>
<section><h2>Connect Steam</h2><p>Your console address: <strong id="address"></strong>. Detected automatically.</p><button id="loader">Generate Steam loader</button><textarea id="code" readonly aria-label="Steam loader code"></textarea><p id="loaderHelp">In the Steam client, replace the CODE contents with this line and click Engage.</p><button id="revoke">Revoke all Steam connections</button></section>
<section><h2>Return to dashboard</h2><a href="/">Return to dashboard</a><p>Use X in Steam to move the Steam group headless before closing the game. ALData setup is optional and available from the market.</p><button id="invite" hidden>Pair another browser</button><p id="invitation"></p></section></main>
<script>
const el=id=>document.getElementById(id);let serverAddress=location.origin;el('address').textContent=serverAddress;
async function call(path,body){const r=await fetch('/setup/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error);return data;}
const action=(id,fn)=>el(id).onclick=async()=>{el(id).disabled=true;el('error').textContent='';try{await fn()}catch(e){el('error').textContent=e.message}finally{el(id).disabled=false}};
async function refresh(){try{const s=await call('state');serverAddress=s.serverAddress||location.origin;el('address').textContent=serverAddress;el('pair').hidden=true;el('settings').hidden=false;el('account').hidden=!s.canConfigureAccount||s.configured;el('invite').hidden=!s.requirePairing;el('loaderHelp').textContent=s.requirePairing?'In the Steam client, replace the CODE contents with this line and click Engage. Keep it private: it grants control of this server.':'In the Steam client, replace the CODE contents with this line and click Engage. Anyone who can reach this server can connect while pairing is off.';el('error').textContent=s.configured?'Account configured. Open the dashboard or connect Steam.':''}catch(e){el('pair').hidden=false;el('error').textContent=e.message}}
action('pairButton',async()=>{await call('pair',{token:location.hash.slice(1)});history.replaceState(null,'','/setup');await refresh()});
action('connect',async()=>{await call('session',{session:el('session').value,realm:el('realm').value});el('session').value='';await refresh();el('error').textContent='Account connected. Dashboard is starting; select your characters there.'});
action('loader',async()=>{const r=await call('steam',{origin:serverAddress});el('code').value=r.code});
action('revoke',async()=>{if(confirm('Revoke every private Steam token? Direct tokenless loaders are unaffected. Running headless characters continue.')){await call('revoke',{});el('code').value='';el('error').textContent='Steam credentials revoked. Generate a new loader to reconnect.'}});
action('invite',async()=>{const r=await call('invite',{});el('invitation').textContent=location.origin+'/setup#'+r.token});refresh();
</script></body></html>`;
