"use client";

export const STAT_SCROLLS = [
  {
    stat: "str",
    scroll: "strscroll",
    label: "STR",
    multiplier: 1,
    purchasable: true,
  },
  {
    stat: "int",
    scroll: "intscroll",
    label: "INT",
    multiplier: 1,
    purchasable: true,
  },
  {
    stat: "dex",
    scroll: "dexscroll",
    label: "DEX",
    multiplier: 1,
    purchasable: true,
  },
  {
    stat: "vit",
    scroll: "vitscroll",
    label: "VIT",
    multiplier: 1,
    purchasable: true,
  },
  {
    stat: "for",
    scroll: "forscroll",
    label: "FOR",
    multiplier: 1,
    purchasable: false,
  },
  {
    stat: "evasion",
    scroll: "evasionscroll",
    label: "Evasion",
    multiplier: 0.325,
    purchasable: false,
  },
  {
    stat: "reflection",
    scroll: "reflectionscroll",
    label: "Reflection",
    multiplier: 0.15,
    purchasable: false,
  },
  {
    stat: "gold",
    scroll: "goldscroll",
    label: "Gold",
    multiplier: 0.5,
    purchasable: false,
  },
  {
    stat: "luck",
    scroll: "luckscroll",
    label: "Luck",
    multiplier: 1,
    purchasable: false,
  },
  {
    stat: "xp",
    scroll: "xpscroll",
    label: "XP",
    multiplier: 0.5,
    purchasable: false,
  },
  {
    stat: "armor",
    scroll: "armorscroll",
    label: "Armor",
    multiplier: 2.25,
    purchasable: false,
  },
  {
    stat: "resistance",
    scroll: "resistancescroll",
    label: "Resistance",
    multiplier: 2.25,
    purchasable: false,
  },
  {
    stat: "speed",
    scroll: "speedscroll",
    label: "Speed",
    multiplier: 0.325,
    purchasable: false,
  },
  {
    stat: "lifesteal",
    scroll: "lifestealscroll",
    label: "Lifesteal",
    multiplier: 0.15,
    purchasable: false,
  },
  {
    stat: "manasteal",
    scroll: "manastealscroll",
    label: "Manasteal",
    multiplier: 0.04,
    purchasable: false,
  },
  {
    stat: "rpiercing",
    scroll: "rpiercingscroll",
    label: "Resistance piercing",
    multiplier: 2.25,
    purchasable: false,
  },
  {
    stat: "apiercing",
    scroll: "apiercingscroll",
    label: "Armor piercing",
    multiplier: 2.25,
    purchasable: false,
  },
  {
    stat: "crit",
    scroll: "critscroll",
    label: "Critical hit",
    multiplier: 0.125,
    purchasable: false,
  },
  {
    stat: "dreturn",
    scroll: "dreturnscroll",
    label: "Damage return",
    multiplier: 0.5,
    purchasable: false,
  },
  {
    stat: "frequency",
    scroll: "frequencyscroll",
    label: "Attack speed",
    multiplier: 0.325,
    purchasable: false,
  },
  {
    stat: "mp_cost",
    scroll: "mpcostscroll",
    label: "MP cost reduction",
    multiplier: 0.6,
    purchasable: false,
  },
  {
    stat: "output",
    scroll: "outputscroll",
    label: "Output",
    multiplier: 0.175,
    purchasable: false,
  },
] as const;
